version: '3.1'

services:
  docs:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        nginx_conf: ./docker/nginx.conf
    ports:
      - "3000:80"
      - "3443:443"