version: '3.1'

services:
  docs:
    image: mesosphere/dcos-docs-site
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.docs
      args:
        nginx_dir: ./docker/nginx
        git_branch: ${GIT_BRANCH}
        algolia_update: ${ALGOLIA_UPDATE}
        algolia_project_id: ${ALGOLIA_PROJECT_ID}
        algolia_public_key: ${ALGOLIA_PUBLIC_KEY}
        algolia_private_key: ${ALGOLIA_PRIVATE_KEY}
        algolia_index: ${ALGOLIA_INDEX}
        algolia_clear_index: ${ALGOLIA_CLEAR_INDEX}
        LATEST_MDFILES: ${LATEST_MDFILES}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - build:/src
      - build-pdf:/src/build-pdf
  pdf:
    image: mesosphere/dcos-docs-pdf
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.htmltopdf
      args:
        git_branch: ${GIT_BRANCH}
        LATEST_MDFILES: ${LATEST_MDFILES}
        GIT_HASH_TRIM: ${GIT_HASH_TRIM}
        DATE_LAST_SUCCESSFUL_COMMIT: ${DATE_LAST_SUCCESSFUL_COMMIT}
        LAST_SUCCESSFUL_BUILD: ${LAST_SUCCESSFUL_BUILD}
    environment:
      - LATEST_MDFILES=${LATEST_MDFILES}
      - GIT_HASH_TRIM=${GIT_HASH_TRIM}
      - DATE_LAST_SUCCESSFUL_COMMIT=${DATE_LAST_SUCCESSFUL_COMMIT}
      - LAST_SUCCESSFUL_BUILD=${LAST_SUCCESSFUL_BUILD}
    volumes:
      - build-pdf:/src/build-pdf
  test:
    depends_on:
      - docs
    image: 18fgsa/html-proofer
    volumes:
      - build:/src
    command: /src/build --empty-alt-ignore --url-swap "\/pdf\/:file\:\/\/\/src\/build-pdf\/"
volumes:
  build:
  build-pdf:
