version: '3.1'

services:
  linkchecker:
    image: mesosphere/linkchecker
    links:
      - "docs:docs"
    working_dir: /workdir
    command: >
      bash -c "mkdir -p -m 777 reports && \
              linkchecker \
              --complete \
              --anchors \
              --check-extern \
              --user-agent="curl/7.24.0" \
              --output=text \
              --file-output="csv/reports/linkchecker.csv" \
              --file-output="html/reports/linkchecker.html" \
              http://"
    volumes:
      - ../linkchecker:/workdir
