# Common values:

packageName: prometheus
serviceName: prometheus
techName:  Prometheus
techShortName: Prometheus

# Values specific to certain templates:

security:
  plaintext: ", \"allow_plaintext\": <true|false default false>"
